set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

set -g @menus_trigger 'F1'
set -g status-left '#{prefix_highlight} [#S] '

# Alt+Arrow to switch panes without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Initialize TPM (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
